package ru.govno.client.module;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import ru.govno.client.module.modules.AimAssist;
import ru.govno.client.module.modules.AirJump;
import ru.govno.client.module.modules.AntiBot;
import ru.govno.client.module.modules.AntiCrystal;
import ru.govno.client.module.modules.AutoApple;
import ru.govno.client.module.modules.AutoCrystal;
import ru.govno.client.module.modules.AutoLeave;
import ru.govno.client.module.modules.AutoWebTrap;
import ru.govno.client.module.modules.BowAimbot;
import ru.govno.client.module.modules.BowSpam;
import ru.govno.client.module.modules.Bypass;
import ru.govno.client.module.modules.CaveFinder;
import ru.govno.client.module.modules.Charming;
import ru.govno.client.module.modules.ChatHelper;
import ru.govno.client.module.modules.ChestStealer;
import ru.govno.client.module.modules.ClickGui;
import ru.govno.client.module.modules.ClickTeleport;
import ru.govno.client.module.modules.ClientColors;
import ru.govno.client.module.modules.ClientTune;
import ru.govno.client.module.modules.ComfortUi;
import ru.govno.client.module.modules.CommandGui;
import ru.govno.client.module.modules.Criticals;
import ru.govno.client.module.modules.Crosshair;
import ru.govno.client.module.modules.CrystalBooster;
import ru.govno.client.module.modules.DashCubics;
import ru.govno.client.module.modules.DashTrail;
import ru.govno.client.module.modules.DeathBox;
import ru.govno.client.module.modules.ESP;
import ru.govno.client.module.modules.ElytraBoost;
import ru.govno.client.module.modules.EntityBox;
import ru.govno.client.module.modules.FakePlayer;
import ru.govno.client.module.modules.FireFlies;
import ru.govno.client.module.modules.Fly;
import ru.govno.client.module.modules.FragEffects;
import ru.govno.client.module.modules.FreeCam;
import ru.govno.client.module.modules.GameSyncTPS;
import ru.govno.client.module.modules.HighJump;
import ru.govno.client.module.modules.HitAura;
import ru.govno.client.module.modules.HitBubble;
import ru.govno.client.module.modules.HoleESP;
import ru.govno.client.module.modules.Hud;
import ru.govno.client.module.modules.InfHVHHelper;
import ru.govno.client.module.modules.InvMngr;
import ru.govno.client.module.modules.InvWalk;
import ru.govno.client.module.modules.JesusSpeed;
import ru.govno.client.module.modules.JumpCircles;
import ru.govno.client.module.modules.LineGlyphs;
import ru.govno.client.module.modules.LongJump;
import ru.govno.client.module.modules.MiddleClick;
import ru.govno.client.module.modules.MiniMap;
import ru.govno.client.module.modules.MoveHelper;
import ru.govno.client.module.modules.NameSecurity;
import ru.govno.client.module.modules.NameTags;
import ru.govno.client.module.modules.NoClip;
import ru.govno.client.module.modules.NoInteract;
import ru.govno.client.module.modules.NoRender;
import ru.govno.client.module.modules.Notifications;
import ru.govno.client.module.modules.Nuker;
import ru.govno.client.module.modules.OffHand;
import ru.govno.client.module.modules.OnFalling;
import ru.govno.client.module.modules.Particles;
import ru.govno.client.module.modules.PearlFlight;
import ru.govno.client.module.modules.Phase;
import ru.govno.client.module.modules.PickBlowup;
import ru.govno.client.module.modules.PlayerHelper;
import ru.govno.client.module.modules.PotionThrower;
import ru.govno.client.module.modules.ProContainer;
import ru.govno.client.module.modules.PushAttack;
import ru.govno.client.module.modules.Respawn;
import ru.govno.client.module.modules.STabMonitor;
import ru.govno.client.module.modules.ScaffWalk;
import ru.govno.client.module.modules.Scaffold;
import ru.govno.client.module.modules.SchoolBoy;
import ru.govno.client.module.modules.SexAura;
import ru.govno.client.module.modules.Speed;
import ru.govno.client.module.modules.Spider;
import ru.govno.client.module.modules.StormHVHHelper;
import ru.govno.client.module.modules.Strafe;
import ru.govno.client.module.modules.Surround;
import ru.govno.client.module.modules.TPExploit;
import ru.govno.client.module.modules.TPInfluence;
import ru.govno.client.module.modules.TargetHUD;
import ru.govno.client.module.modules.TargetStrafe;
import ru.govno.client.module.modules.ThrowDirs;
import ru.govno.client.module.modules.ThrowFollow;
import ru.govno.client.module.modules.ThrowPetard;
import ru.govno.client.module.modules.Timer;
import ru.govno.client.module.modules.TopkaSort;
import ru.govno.client.module.modules.TotemPopESP;
import ru.govno.client.module.modules.TpDirections;
import ru.govno.client.module.modules.Tracers;
import ru.govno.client.module.modules.Trails;
import ru.govno.client.module.modules.Triangular;
import ru.govno.client.module.modules.VClip;
import ru.govno.client.module.modules.Velocity;
import ru.govno.client.module.modules.ViewModel;
import ru.govno.client.module.modules.WallHack;
import ru.govno.client.module.modules.WaterSpeed;
import ru.govno.client.module.modules.WorldRender;
import ru.govno.client.module.modules.Xray;
import ru.govno.client.newfont.Fonts;
import ru.govno.client.utils.CrystalField;

public class ModuleManager {
   public List<Module> modules = new ArrayList<>();
   public List<String> moduleDescription = new ArrayList<>();

   public ModuleManager() {
      this.modules.add(new ClientColors());
      this.modules.add(new SexAura());
      this.modules.add(new PickBlowup());
      this.modules.add(new FireFlies());
      this.modules.add(new HitBubble());
      this.modules.add(new STabMonitor());
      this.modules.add(new WallHack());
      this.modules.add(new ScaffWalk());
      this.modules.add(new HitAura());
      this.modules.add(new CommandGui());
      this.modules.add(new StormHVHHelper());
      this.modules.add(new PotionThrower());
      this.modules.add(new Charming());
      this.modules.add(new Triangular());
      this.modules.add(new ESP());
      this.modules.add(new DeathBox());
      this.modules.add(new AutoLeave());
      this.modules.add(new JumpCircles());
      this.modules.add(new CrystalField());
      this.modules.add(new WorldRender());
      this.modules.add(new PlayerHelper());
      this.modules.add(new MoveHelper());
      this.modules.add(new TotemPopESP());
      this.modules.add(new HoleESP());
      this.modules.add(new GameSyncTPS());
      this.modules.add(new Nuker());
      this.modules.add(new LineGlyphs());
      this.modules.add(new SchoolBoy());
      this.modules.add(new AutoWebTrap());
      this.modules.add(new AimAssist());
      this.modules.add(new Hud());
      this.modules.add(new ClickGui());
      this.modules.add(new Surround());
      this.modules.add(new ComfortUi());
      this.modules.add(new Phase());
      this.modules.add(new TPExploit());
      this.modules.add(new ChestStealer());
      this.modules.add(new Velocity());
      this.modules.add(new Speed());
      this.modules.add(new WaterSpeed());
      this.modules.add(new PushAttack());
      this.modules.add(new JesusSpeed());
      this.modules.add(new NoClip());
      this.modules.add(new FreeCam());
      this.modules.add(new AirJump());
      this.modules.add(new HighJump());
      this.modules.add(new AntiCrystal());
      this.modules.add(new PearlFlight());
      this.modules.add(new Scaffold());
      this.modules.add(new BowSpam());
      this.modules.add(new EntityBox());
      this.modules.add(new Particles());
      this.modules.add(new AutoCrystal());
      this.modules.add(new TargetHUD());
      this.modules.add(new Trails());
      this.modules.add(new Notifications());
      this.modules.add(new NameSecurity());
      this.modules.add(new Xray());
      this.modules.add(new ClientTune());
      this.modules.add(new ChatHelper());
      this.modules.add(new NoInteract());
      this.modules.add(new ClickTeleport());
      this.modules.add(new AntiBot());
      this.modules.add(new TopkaSort());
      this.modules.add(new VClip());
      this.modules.add(new LongJump());
      this.modules.add(new ElytraBoost());
      this.modules.add(new Respawn());
      this.modules.add(new BowAimbot());
      this.modules.add(new OffHand());
      this.modules.add(new Criticals());
      this.modules.add(new Bypass());
      this.modules.add(new AutoApple());
      this.modules.add(new ProContainer());
      this.modules.add(new OnFalling());
      this.modules.add(new TargetStrafe());
      this.modules.add(new ViewModel());
      this.modules.add(new InvMngr());
      this.modules.add(new NoRender());
      this.modules.add(new Crosshair());
      this.modules.add(new Fly());
      this.modules.add(new FakePlayer());
      this.modules.add(new Spider());
      this.modules.add(new InvWalk());
      this.modules.add(new Timer());
      this.modules.add(new NameTags());
      this.modules.add(new Tracers());
      this.modules.add(new Strafe());
      this.modules.add(new MiddleClick());
      this.modules.add(new DashTrail());
      this.modules.add(new TpDirections());
      this.modules.add(new ThrowDirs());
      this.modules.add(new TPInfluence());
      this.modules.add(new CaveFinder());
      this.modules.add(new InfHVHHelper());
      this.modules.add(new FragEffects());
      this.modules.add(new DashCubics());
      this.modules.add(new CrystalBooster());
      this.modules.add(new MiniMap());
      this.modules.add(new ThrowPetard());
      this.modules.add(new ThrowFollow());
      this.moduleDescription.add("SexAuraПялит в жопу игроков");
      this.moduleDescription.add("FireFliesВокруг вас будут летать светлячки");
      this.moduleDescription.add("HitBubbleКрасивые эффекты от удара");
      this.moduleDescription.add("PickBlowupРисует кружки под предметами которые были подобраны вами");
      this.moduleDescription.add("WallHackВидно существ через стены");
      this.moduleDescription.add("ScaffWalkСтроит мост блоками");
      this.moduleDescription.add("HitAuraСамостоятельно убивает всё живое в радиусе действия");
      this.moduleDescription.add("CommandGuiУдобное использование комманд мышкой");
      this.moduleDescription.add("StormHVHHelperПомогает играть на шторм хвх");
      this.moduleDescription.add("PotionThrowerСамостоятельно кидает полезные зелья");
      this.moduleDescription.add("CharmingЛетающий приятель");
      this.moduleDescription.add("TriangularПоказывает стрелки ведущие к существам");
      this.moduleDescription.add("ESPАналогия Wallhack.");
      this.moduleDescription.add("DeathBoxОставляет информативный бокс с тегом при смерти существ.");
      this.moduleDescription.add("AutoLeaveИзбегает контакта с игроками.");
      this.moduleDescription.add("JumpCirclesРисует круги от прышка");
      this.moduleDescription.add("CrystalFieldКристальный пвп бот, умеет самостоятельно ставить обсидиан");
      this.moduleDescription.add("WorldRenderУкрашает игру");
      this.moduleDescription.add("PlayerHelperПрофессионал в помощи поставке/ломании блоков и подобное");
      this.moduleDescription.add("MoveHelperВспомогательный инструмент для движений");
      this.moduleDescription.add("TotemPopESPСпавнит приведение при использовании тотема любым игроком");
      this.moduleDescription.add("HoleESPПодсвечивает ''холки'' куда можно прыгнуть");
      this.moduleDescription.add("GameSyncTPSСинхронизирует игру с сервером");
      this.moduleDescription.add("NukerЛомает блоки вокруг вас");
      this.moduleDescription.add("LineGlyphsРисует метричные линии в мире");
      this.moduleDescription.add("SchoolBoyУменьшает существ до роста ''детей''");
      this.moduleDescription.add("AutoWebTrapСтавит паутину в существ/игроков");
      this.moduleDescription.add("AimAssistПомогает прицеливаться в пвп");
      this.moduleDescription.add("HudДобавляет оверлей клиента");
      this.moduleDescription.add("ClickGuiМеню этого чита");
      this.moduleDescription.add("SurroundСтавит вокруг вас обсидиан");
      this.moduleDescription.add("ComfortUiДобавляет приятное затемнение во всех меню");
      this.moduleDescription.add("PhaseДаёт пройти в стену");
      this.moduleDescription.add("TPExploitТелепортирует на старую точку");
      this.moduleDescription.add("ChestStealerЛутает сундуки");
      this.moduleDescription.add("VelocityБлокирует откидывание");
      this.moduleDescription.add("SpeedУскоряет передвижение");
      this.moduleDescription.add("WaterSpeedУскоряет в воде");
      this.moduleDescription.add("PushAttackПозволяет бить и использовать предметы");
      this.moduleDescription.add("JesusSpeedПозволяет бегать/летать по воде");
      this.moduleDescription.add("NoClipХодьба/телепорт сквозь блоки");
      this.moduleDescription.add("FreeCamКамера обзора местности");
      this.moduleDescription.add("AirJumpПрыжки от воздухa");
      this.moduleDescription.add("HighJumpУвеличивает высоту прыжка");
      this.moduleDescription.add("AntiCrystalБлокирует обсидиан/бедрок блоками");
      this.moduleDescription.add("PearlFlightПолёт от урона эндер жемчуга");
      this.moduleDescription.add("ScaffoldСтроит мост блоками");
      this.moduleDescription.add("BowSpamБыстро стреляет луком");
      this.moduleDescription.add("EntityBoxИзменяет боксы существ и может сделать ваши руки 'длиннее'");
      this.moduleDescription.add("ParticlesЛетающие частицы от урона");
      this.moduleDescription.add("AutoCrystalСам ставит/взрывает кристалл на поставленный обсидиан");
      this.moduleDescription.add("TargetHUDРисует табличку с информацией о текущем таргете");
      this.moduleDescription.add("TrailsОставляет шлейф от ходьбы");
      this.moduleDescription.add("NotificationsПоказывает уведомления");
      this.moduleDescription.add("NameSecurityСкрывает ваш никнейм");
      this.moduleDescription.add("XrayИщет руды через стены");
      this.moduleDescription.add("ClientTuneВоспроизводит звуки клиента");
      this.moduleDescription.add("ChatHelperВспомогательный бот для чата");
      this.moduleDescription.add("NoInteractБлокирует клик по умным блокам");
      this.moduleDescription.add("ClickTeleportТелепортирует при пкм по взгляду");
      this.moduleDescription.add("AntiBotУдаляет ботов из мира");
      this.moduleDescription.add("TopkaSortСортирует кучу ресурсов под вами");
      this.moduleDescription.add("VClipВертикальный телепорт");
      this.moduleDescription.add("LongJumpПолёт/ускорение от урона");
      this.moduleDescription.add("ElytraBoostПолёт/ускорение с элитрами");
      this.moduleDescription.add("RespawnАвтоматически возраждает вас");
      this.moduleDescription.add("BowAimbotАвтоматичетки наводится на существ луком учитывая траекторию полёта стрелы");
      this.moduleDescription.add("OffHandУмно использует тотемы и прочие предметы левой рукой");
      this.moduleDescription.add("CriticalsПри возможности наносит увеличенный урон");
      this.moduleDescription.add("BypassОслабляет воздействие античита");
      this.moduleDescription.add("AutoAppleАвтоматически хилится золотыми яблоками");
      this.moduleDescription.add("ProContainerУпрощает работу с инвентарём");
      this.moduleDescription.add("OnFallingДейсвует при падении с высоты");
      this.moduleDescription.add("TargetStrafeБегает вокруг противника Aura");
      this.moduleDescription.add("ViewModelМеняет позицию рук");
      this.moduleDescription.add("InvMngrСортирует/чистит инвентарь");
      this.moduleDescription.add("NoRenderУбирает мешающие элементы игры");
      this.moduleDescription.add("CrosshairМеняет вид прицела на экране");
      this.moduleDescription.add("FlyСимулятор голубя");
      this.moduleDescription.add("FakePlayerСпавнит локального бота");
      this.moduleDescription.add("SpiderПозволяет лазить по стенам");
      this.moduleDescription.add("InvWalkХодьба во всех меню");
      this.moduleDescription.add("TimerИзменят скорость времяни игры");
      this.moduleDescription.add("NameTagsПоказывает информацию об игроке над игроком");
      this.moduleDescription.add("TracersРисует линии к игрокам");
      this.moduleDescription.add("StrafeПозволяет ускорить стрейфинг");
      this.moduleDescription.add("BurrowСтавит блок в ноги");
      this.moduleDescription.add("MiddleClickДрузья/пёрл по колесу мыши");
      this.moduleDescription.add("DashTrailСтремительный след с освещением");
      this.moduleDescription.add("TpDirectionsПоказывает сторону телепортации существ");
      this.moduleDescription.add("MiniMap3d мир на 2d миникарте");
      this.moduleDescription.add("ThrowDirsПеред броском предмета уже будет видно путь его движения");
      this.moduleDescription.add("TPInfluenceЭксплоит увеличенной дистанции указанных действий");
      this.moduleDescription.add("CaveFinderПозволяет видеть сквозь стены полости,шахты,каньёны");
      this.moduleDescription.add("InfHVHHelperПомогает играть на инфинити хвх");
      this.moduleDescription.add("FragEffectsЭпичные эффекты убийств");
      this.moduleDescription.add("DashCubicsКубики валяющиеся на земле");
      this.moduleDescription.add("CrystalBoosterУскоряет обработку кристалов игрой");
      this.moduleDescription.add("ThrowPetardВы можете кинуть петарду! ОООДАААА");
      this.moduleDescription.add("ThrowFollowАвтоматически швыряет пёрку в догонку за таргетом");
      this.modules.sort(Comparator.comparing(module -> -Fonts.comfortaaRegular_18.getStringWidth(module.name)));
   }

   public int getEnabledModulesCount() {
      return (int)this.getModuleList().stream().filter(Module::isActived).count();
   }

   public List<Module> getModuleList() {
      return this.modules;
   }

   public List<String> getModuleDescriptionList() {
      return this.moduleDescription;
   }

   public Module getModule(String name) {
      return this.getModuleList().stream().filter(mod -> mod.getName().equalsIgnoreCase(name)).findAny().orElse(null);
   }
}
