package ru.govno.client.module;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import ru.govno.client.module.modules.AimAssist;
import ru.govno.client.module.modules.AirJump;
import ru.govno.client.module.modules.AntiBot;
import ru.govno.client.module.modules.AntiCrystal;
import ru.govno.client.module.modules.AutoApple;
import ru.govno.client.module.modules.AutoCrystal;
import ru.govno.client.module.modules.AutoLeave;
import ru.govno.client.module.modules.AutoWebTrap;
import ru.govno.client.module.modules.BowAimbot;
import ru.govno.client.module.modules.BowSpam;
import ru.govno.client.module.modules.Bypass;
import ru.govno.client.module.modules.CaveFinder;
import ru.govno.client.module.modules.Charming;
import ru.govno.client.module.modules.ChatHelper;
import ru.govno.client.module.modules.ChestStealer;
import ru.govno.client.module.modules.ClickGui;
import ru.govno.client.module.modules.ClickTeleport;
import ru.govno.client.module.modules.ClientColors;
import ru.govno.client.module.modules.ClientTune;
import ru.govno.client.module.modules.ComfortUi;
import ru.govno.client.module.modules.CommandGui;
import ru.govno.client.module.modules.Criticals;
import ru.govno.client.module.modules.Crosshair;
import ru.govno.client.module.modules.CrystalBooster;
import ru.govno.client.module.modules.DashCubics;
import ru.govno.client.module.modules.DashTrail;
import ru.govno.client.module.modules.DeathBox;
import ru.govno.client.module.modules.ESP;
import ru.govno.client.module.modules.ElytraBoost;
import ru.govno.client.module.modules.EntityBox;
import ru.govno.client.module.modules.FakePlayer;
import ru.govno.client.module.modules.FireFlies;
import ru.govno.client.module.modules.Fly;
import ru.govno.client.module.modules.FragEffects;
import ru.govno.client.module.modules.FreeCam;
import ru.govno.client.module.modules.GameSyncTPS;
import ru.govno.client.module.modules.HighJump;
import ru.govno.client.module.modules.HitAura;
import ru.govno.client.module.modules.HitBubble;
import ru.govno.client.module.modules.HoleESP;
import ru.govno.client.module.modules.Hud;
import ru.govno.client.module.modules.InfHVHHelper;
import ru.govno.client.module.modules.InvMngr;
import ru.govno.client.module.modules.InvWalk;
import ru.govno.client.module.modules.JesusSpeed;
import ru.govno.client.module.modules.JumpCircles;
import ru.govno.client.module.modules.LineGlyphs;
import ru.govno.client.module.modules.LongJump;
import ru.govno.client.module.modules.MiddleClick;
import ru.govno.client.module.modules.MiniMap;
import ru.govno.client.module.modules.MoveHelper;
import ru.govno.client.module.modules.NameSecurity;
import ru.govno.client.module.modules.NameTags;
import ru.govno.client.module.modules.NoClip;
import ru.govno.client.module.modules.NoInteract;
import ru.govno.client.module.modules.NoRender;
import ru.govno.client.module.modules.Notifications;
import ru.govno.client.module.modules.Nuker;
import ru.govno.client.module.modules.OffHand;
import ru.govno.client.module.modules.OnFalling;
import ru.govno.client.module.modules.Particles;
import ru.govno.client.module.modules.PearlFlight;
import ru.govno.client.module.modules.Phase;
import ru.govno.client.module.modules.PickBlowup;
import ru.govno.client.module.modules.PlayerHelper;
import ru.govno.client.module.modules.PotionThrower;
import ru.govno.client.module.modules.ProContainer;
import ru.govno.client.module.modules.PushAttack;
import ru.govno.client.module.modules.Respawn;
import ru.govno.client.module.modules.STabMonitor;
import ru.govno.client.module.modules.ScaffWalk;
import ru.govno.client.module.modules.Scaffold;
import ru.govno.client.module.modules.SchoolBoy;
import ru.govno.client.module.modules.SexAura;
import ru.govno.client.module.modules.Speed;
import ru.govno.client.module.modules.Spider;
import ru.govno.client.module.modules.StormHVHHelper;
import ru.govno.client.module.modules.Strafe;
import ru.govno.client.module.modules.Surround;
import ru.govno.client.module.modules.TPExploit;
import ru.govno.client.module.modules.TPInfluence;
import ru.govno.client.module.modules.TargetHUD;
import ru.govno.client.module.modules.TargetStrafe;
import ru.govno.client.module.modules.ThrowDirs;
import ru.govno.client.module.modules.ThrowFollow;
import ru.govno.client.module.modules.ThrowPetard;
import ru.govno.client.module.modules.Timer;
import ru.govno.client.module.modules.TopkaSort;
import ru.govno.client.module.modules.TotemPopESP;
import ru.govno.client.module.modules.TpDirections;
import ru.govno.client.module.modules.Tracers;
import ru.govno.client.module.modules.Trails;
import ru.govno.client.module.modules.Triangular;
import ru.govno.client.module.modules.VClip;
import ru.govno.client.module.modules.Velocity;
import ru.govno.client.module.modules.ViewModel;
import ru.govno.client.module.modules.WallHack;
import ru.govno.client.module.modules.WaterSpeed;
import ru.govno.client.module.modules.WorldRender;
import ru.govno.client.module.modules.Xray;
import ru.govno.client.newfont.Fonts;
import ru.govno.client.utils.CrystalField;

// TODO: Translate

public class ModuleManager {
   public List<Module> modules = new ArrayList<>();
   public List<String> moduleDescription = new ArrayList<>();

   public ModuleManager() {
      this.modules.add(new ClientColors());
      this.modules.add(new SexAura());
      this.modules.add(new PickBlowup());
      this.modules.add(new FireFlies());
      this.modules.add(new HitBubble());
      this.modules.add(new STabMonitor());
      this.modules.add(new WallHack());
      this.modules.add(new ScaffWalk());
      this.modules.add(new HitAura());
      this.modules.add(new CommandGui());
      this.modules.add(new StormHVHHelper());
      this.modules.add(new PotionThrower());
      this.modules.add(new Charming());
      this.modules.add(new Triangular());
      this.modules.add(new ESP());
      this.modules.add(new DeathBox());
      this.modules.add(new AutoLeave());
      this.modules.add(new JumpCircles());
      this.modules.add(new CrystalField());
      this.modules.add(new WorldRender());
      this.modules.add(new PlayerHelper());
      this.modules.add(new MoveHelper());
      this.modules.add(new TotemPopESP());
      this.modules.add(new HoleESP());
      this.modules.add(new GameSyncTPS());
      this.modules.add(new Nuker());
      this.modules.add(new LineGlyphs());
      this.modules.add(new SchoolBoy());
      this.modules.add(new AutoWebTrap());
      this.modules.add(new AimAssist());
      this.modules.add(new Hud());
      this.modules.add(new ClickGui());
      this.modules.add(new Surround());
      this.modules.add(new ComfortUi());
      this.modules.add(new Phase());
      this.modules.add(new TPExploit());
      this.modules.add(new ChestStealer());
      this.modules.add(new Velocity());
      this.modules.add(new Speed());
      this.modules.add(new WaterSpeed());
      this.modules.add(new PushAttack());
      this.modules.add(new JesusSpeed());
      this.modules.add(new NoClip());
      this.modules.add(new FreeCam());
      this.modules.add(new AirJump());
      this.modules.add(new HighJump());
      this.modules.add(new AntiCrystal());
      this.modules.add(new PearlFlight());
      this.modules.add(new Scaffold());
      this.modules.add(new BowSpam());
      this.modules.add(new EntityBox());
      this.modules.add(new Particles());
      this.modules.add(new AutoCrystal());
      this.modules.add(new TargetHUD());
      this.modules.add(new Trails());
      this.modules.add(new Notifications());
      this.modules.add(new NameSecurity());
      this.modules.add(new Xray());
      this.modules.add(new ClientTune());
      this.modules.add(new ChatHelper());
      this.modules.add(new NoInteract());
      this.modules.add(new ClickTeleport());
      this.modules.add(new AntiBot());
      this.modules.add(new TopkaSort());
      this.modules.add(new VClip());
      this.modules.add(new LongJump());
      this.modules.add(new ElytraBoost());
      this.modules.add(new Respawn());
      this.modules.add(new BowAimbot());
      this.modules.add(new OffHand());
      this.modules.add(new Criticals());
      this.modules.add(new Bypass());
      this.modules.add(new AutoApple());
      this.modules.add(new ProContainer());
      this.modules.add(new OnFalling());
      this.modules.add(new TargetStrafe());
      this.modules.add(new ViewModel());
      this.modules.add(new InvMngr());
      this.modules.add(new NoRender());
      this.modules.add(new Crosshair());
      this.modules.add(new Fly());
      this.modules.add(new FakePlayer());
      this.modules.add(new Spider());
      this.modules.add(new InvWalk());
      this.modules.add(new Timer());
      this.modules.add(new NameTags());
      this.modules.add(new Tracers());
      this.modules.add(new Strafe());
      this.modules.add(new MiddleClick());
      this.modules.add(new DashTrail());
      this.modules.add(new TpDirections());
      this.modules.add(new ThrowDirs());
      this.modules.add(new TPInfluence());
      this.modules.add(new CaveFinder());
      this.modules.add(new InfHVHHelper());
      this.modules.add(new FragEffects());
      this.modules.add(new DashCubics());
      this.modules.add(new CrystalBooster());
      this.modules.add(new MiniMap());
      this.modules.add(new ThrowPetard());
      this.modules.add(new ThrowFollow());
      this.moduleDescription.add("SexAuraПялит в жопу игроков");
      this.moduleDescription.add("FireFliesFireflies will fly around you");
      this.moduleDescription.add("HitBubbleBeautiful impact effects");
      this.moduleDescription.add("PickBlowupРисует кружки под предметами которые были подобраны вами");
      this.moduleDescription.add("WallHackLets you look through walls");
      this.moduleDescription.add("ScaffWalkBuilds a bridge with blocks");
      this.moduleDescription.add("HitAuraAutomatically kills/attacks all living creatures within its range");
      this.moduleDescription.add("CommandGuiУдобное использование комманд мышкой");
      this.moduleDescription.add("StormHVHHelperHelps to play on the storm xvx");
      this.moduleDescription.add("PotionThrowerThrows useful potions at you");
      this.moduleDescription.add("CharmingYour flying Buddy");
      this.moduleDescription.add("TriangularShows pointing arrows leading to creatures");
      this.moduleDescription.add("ESPHighlights players through walls");
      this.moduleDescription.add("DeathBoxLeaves an informative box with a tag when creatures die");
      this.moduleDescription.add("AutoLeaveAvoids contact with players");
      this.moduleDescription.add("JumpCirclesDraws circles from jumping");
      this.moduleDescription.add("CrystalFieldCrystal pvp bot, can independently place obsidian");
      this.moduleDescription.add("WorldRenderDecorates the game");
      this.moduleDescription.add("PlayerHelperПрофессионал в помощи поставке/ломании блоков и подобное");
      this.moduleDescription.add("MoveHelperMovement aid");
      this.moduleDescription.add("TotemPopESPSpawns a ghost when popping someones Totem");
      this.moduleDescription.add("HoleESPHighlights holes where you can jump");
      this.moduleDescription.add("GameSyncTPSСSynchronizes the game with the server");
      this.moduleDescription.add("NukerBreaks blocks around you");
      this.moduleDescription.add("LineGlyphsDraws metric lines in the world");
      this.moduleDescription.add("SchoolBoyShrinks creatures to the height of ''children''");
      this.moduleDescription.add("AutoWebTrapСтавит паутину в существ/игроков");
      this.moduleDescription.add("AimAssistHelps with aiming in PvP");
      this.moduleDescription.add("HudAdds a client overlay");
      this.moduleDescription.add("ClickGuiMenu for this client");
      this.moduleDescription.add("SurroundPlaces obsidian around you");
      this.moduleDescription.add("ComfortUiAdds a nice dimming effect to all menus");
      this.moduleDescription.add("PhaseLets you go through the wall");
      this.moduleDescription.add("TPExploitTeleports to your previously saved point");
      this.moduleDescription.add("ChestStealerLoots chests");
      this.moduleDescription.add("VelocityБлокирует откидывание");
      this.moduleDescription.add("SpeedSpeeds up movement");
      this.moduleDescription.add("WaterSpeedAccelerates in water");
      this.moduleDescription.add("PushAttackПозволяет бить и использовать предметы");
      this.moduleDescription.add("JesusSpeedAllows you to run and fly on water");
      this.moduleDescription.add("NoClipWalk/Teleport through blocks");
      this.moduleDescription.add("FreeCamAllows you to view any place near you without actually moving");
      this.moduleDescription.add("AirJumpJumping in air");
      this.moduleDescription.add("HighJumpIncreases jump height");
      this.moduleDescription.add("AntiCrystalBlocks obsidian and bedrock with blocks");
      this.moduleDescription.add("PearlFlightFlight from ender pearl damage");
      this.moduleDescription.add("ScaffoldBuilds a bridge with blocks");
      this.moduleDescription.add("BowSpamShoots a bow quickly");
      this.moduleDescription.add("EntityBoxChanges creatures hit box and can make your arms 'longer'");
      this.moduleDescription.add("ParticlesFlying Damage Particles");
      this.moduleDescription.add("AutoCrystalPuts crystals on obsidian and explodes it");
      this.moduleDescription.add("TargetHUDDraws a sign with information about the current target");
      this.moduleDescription.add("TrailsLeaves a trail behind you from walking");
      this.moduleDescription.add("NotificationsShows client notifications");
      this.moduleDescription.add("NameSecurityHides your nickname");
      this.moduleDescription.add("XrayShows you ores through walls");
      this.moduleDescription.add("ClientTunePlays client sounds");
      this.moduleDescription.add("ChatHelperHelper chat bot");
      this.moduleDescription.add("NoInteractБлокирует клик по умным блокам");
      this.moduleDescription.add("ClickTeleportTeleports with right-click on sight");
      this.moduleDescription.add("AntiBotRemoves bots from the world");
      this.moduleDescription.add("TopkaSortSorts a bunch of resources on ground");
      this.moduleDescription.add("VClipVertical teleport");
      this.moduleDescription.add("LongJumpJump acceleration");
      this.moduleDescription.add("ElytraBoostFlight acceleration with elytra");
      this.moduleDescription.add("RespawnAutomatically respawns you");
      this.moduleDescription.add("BowAimbotAutomatically aims at creatures with a bow, taking into account the flight path of the arrow");
      this.moduleDescription.add("OffHandCleverly uses totems and other objects with his left hand");
      this.moduleDescription.add("CriticalsDeals increased damage when possible");
      this.moduleDescription.add("BypassReduces the impact of anti-cheat");
      this.moduleDescription.add("AutoAppleAutomatically eats golden apples");
      this.moduleDescription.add("ProContainerSimplifies work with inventory");
      this.moduleDescription.add("OnFallingEffective when falling from a height");
      this.moduleDescription.add("TargetStrafeRuns around the enemy");
      this.moduleDescription.add("ViewModelChanges hand position");
      this.moduleDescription.add("InvMngrSorts, cleans inventory");
      this.moduleDescription.add("NoRenderRemoves annoying game elements");
      this.moduleDescription.add("CrosshairChanges the appearance of the sight on the screen");
      this.moduleDescription.add("FlyPigeon simulator");
      this.moduleDescription.add("FakePlayerSpawns a local bot");
      this.moduleDescription.add("SpiderAllows you to climb walls");
      this.moduleDescription.add("InvWalkLets you walking while being in Menus");
      this.moduleDescription.add("TimerChange the tick speed of your game");
      this.moduleDescription.add("NameTagsShows player information above the player");
      this.moduleDescription.add("TracersDraws lines pointing to players");
      this.moduleDescription.add("StrafeAllows you to speed up strafing");
      this.moduleDescription.add("BurrowPuts a block on your feet");
      this.moduleDescription.add("MiddleClickFriends of Pearl on the Mouse Wheel");
      this.moduleDescription.add("DashTrailSwift trail with lighting");
      this.moduleDescription.add("TpDirectionsShows the direction in which the player is teleporting");
      this.moduleDescription.add("MiniMap3d world on 2d minimap");
      this.moduleDescription.add("ThrowDirsBefore throwing an object, the path of its movement will already be visible");
      this.moduleDescription.add("TPInfluenceExploit of the increased distance of the specified actions");
      this.moduleDescription.add("CaveFinderAllows you to see caves, mines, canyons through walls");
      this.moduleDescription.add("InfHVHHelperHelps to play on infinity xvx");
      this.moduleDescription.add("FragEffectsEpic kill effects");
      this.moduleDescription.add("DashCubicsCubes lying on the ground");
      this.moduleDescription.add("CrystalBoosterSpeeds up the game's processing of crystals");
      this.moduleDescription.add("ThrowPetardВы можете кинуть петарду! ОООДАААА");
      this.moduleDescription.add("ThrowFollowАвтоматически швыряет пёрку в догонку за таргетом");
      this.modules.sort(Comparator.comparing(module -> -Fonts.comfortaaRegular_18.getStringWidth(module.name)));
   }

   public int getEnabledModulesCount() {
      return (int)this.getModuleList().stream().filter(Module::isActived).count();
   }

   public List<Module> getModuleList() {
      return this.modules;
   }

   public List<String> getModuleDescriptionList() {
      return this.moduleDescription;
   }

   public Module getModule(String name) {
      return this.getModuleList().stream().filter(mod -> mod.getName().equalsIgnoreCase(name)).findAny().orElse(null);
   }
}
